
about :

  name : wEventHandler
  description : Mixin adds events dispatching mechanism to your class. EventHandler provides methods to bind/unbind handler of an event, to handle a specific event only once, to associate an event with a namespace what later make possible to unbind handler of event with help of namespace. EventHandler allows redirecting events to/from another instance. Unlike alternative implementation of the concept, EventHandler is strict by default and force developer to explicitly declare / bind / unbind all events supported by object. Use it to add events dispatching mechanism to your classes and avoid accumulation of technical dept and potential errors.
  version : 0.4.45
  enabled : 1
  interpreters :
  - nodejs >= 6.0.0
  - chrome >= 60.0.0
  - firefox >= 60.0.0
  keywords :
  - wTools

execution :

  scripts :
    test : wtest staging
    docgen : wdocgen staging

path :

  repository : git+https://github.com/Wandalen/wEventHandler.git
  bugs : https://github.com/Wandalen/wEventHandler/issues
  entry.debug : {path::out.debug}/dwtools/abase/____
  entry.release : {path::out.release}/dwtools/abase/____

build :

  .debug.raw.export :
    default : 1
    setting :
      debug : 1
      raw : 1
      export : 1
      filesPath : path::out.debug
      entryPath : path::entry.debug
    steps :
      - build::.debug
      - step::export

  .release.compiled.export :
    setting :
      debug : 0
      raw : 0
      export : 1
      filesPath : path::out.release
      entryPath : path::entry.release
    steps :
      - build::.release.compiled
      - step::export

